spring:
  datasource:
    url: "jdbc:postgresql:/localhost:5432/contact_center_dev"
    username: postgres
    password: coi1751
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  server:
    port: 7777
jwt:
  secret:
    access: djIQjdqidj#*3#Dunh1dodHDU#dOJId3jifhfoIH38j3ido2hfUHiwehefH*h2hup123geheuh8rh'roi3h89hoh
    refresh: jfkJOJ*6flJLJF:EfiehFHieu81oifjhuefwueoi1r4urito2r3uitgtoutIUEIUEITJFJEFKEJFEJFIiefjwf