spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contact_center_dev
    username: postgres
    password: coi1751
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false
  server:
    port: 8080
jwt:
  secret:
    access: fjkfqjfdkJHFjEJFKefejfsdljGIJJLSGafjgyghfjNsfjN141R851975fhsaF252395Yf27562F525UYF255FS4
    refresh: JHWJDHHHajhdhfgjkhfHjafgAh1841hfjh34518fhfEWGT89f8fgWEYUTLyqfHfgdwgghgha17YJFlH2Fhg2YK