### Registration
POST localhost:8080/api/auth/register
content-type: application/json

{
  "username": "director1",
  "password": "director1",
  "firstName": "Сергеев",
  "lastName": "Сергей",
  "role": "ADMIN",
  "email": "director1@gmail.com"
}

### Login first time
POST localhost:8080/api/auth/login
content-type: application/json

{
  "username": "coi175",
  "password": "Coi11042001Gf"
}

### Login with JWT time
GET localhost:8080/api/auth/test
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2kxNzUiLCJleHAiOjE2NzczMzU4MjgsInJvbGUiOiJBRE1JTiJ9.mg8dIGpnK_xiVexMnY9yNOTuQgKqVC49-47wXb_6WeE0vDVT0SL5ez8vtXeQLVW41CX66qbCgp6pdbKcKQVhuA

### getNewAccessToken
POST localhost:8080/api/auth/token
content-type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2kxNzUiLCJleHAiOjE2Nzk5Mjc4ODh9.BOd7EYmSbsFNlDGRMrJXVcssRvbGrQwtVYd48yz15K1XuG3JoAB_IlKB7M2Hq7Ho9Jqq1kD6rQrv14W-mgM7zg"
}


### contactDTO
POST localhost:8080/tasks/manager/create
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2kxNzUiLCJleHAiOjE2NzgyNzI5NzQsInJvbGUiOiJBRE1JTiJ9.FEvCGpEkcKkhfHUrfvdgjKqRJypJg40z2uv7oqq4V-EuifFvS2XDdGQOnYNfuRtJzIySzTLFeJ0K4Td7ZSCByg

[
  {
    "taskDescription": "тест",
    "taskStatus": "NEW",
    "startDate": "2020-12-31T15:53:16",
    "contactId": "12a39c11-4c4d-4a54-9ce9-08e72d6c6d2c",
    "managerId": "0",
    "operatorId": "0"
  }
]